name: 'Auto run at 3'

on:
  push:
  schedule:
    - cron: '0 3 * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Setup python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
    - name: 'Run script'
      env:
        HOSTLOC_USERNAME: ${{ secrets.HOSTLOC_USERNAME }}
        HOSTLOC_PASSWORD: ${{ secrets.HOSTLOC_PASSWORD }}
      run: python hostloc_get_points.py
